#!/usr/bin/env python3
"""
Setup and verify GCP environment for Batch training
Helps configure GCP project, buckets, and permissions
"""

import argparse
import os
import sys
import subprocess
from pathlib import Path


def run_command(cmd, check=True):
    """Run a shell command and return output"""
    try:
        result = subprocess.run(
            cmd,
            shell=True,
            capture_output=True,
            text=True,
            check=check
        )
        return result.returncode == 0, result.stdout.strip(), result.stderr.strip()
    except subprocess.CalledProcessError as e:
        return False, e.stdout, e.stderr


def check_gcloud_installed():
    """Check if gcloud CLI is installed"""
    success, _, _ = run_command("gcloud --version", check=False)
    return success


def check_authenticated():
    """Check if user is authenticated with gcloud"""
    success, _, _ = run_command("gcloud auth application-default print-access-token", check=False)
    return success


def get_current_project():
    """Get current GCP project"""
    success, output, _ = run_command("gcloud config get-value project", check=False)
    if success and output:
        return output
    return None


def enable_apis(project_id):
    """Enable required GCP APIs"""
    apis = [
        "batch.googleapis.com",
        "compute.googleapis.com",
        "storage.googleapis.com",
        "logging.googleapis.com"
    ]

    print("\nEnabling required APIs...")

    for api in apis:
        print(f"  Enabling {api}...")
        success, _, error = run_command(
            f"gcloud services enable {api} --project={project_id}",
            check=False
        )

        if success:
            print(f"    ✓ {api}")
        else:
            print(f"    ✗ Failed to enable {api}")
            print(f"      {error}")


def create_bucket(bucket_name, region):
    """Create GCS bucket if it doesn't exist"""
    # Check if bucket exists
    success, _, _ = run_command(f"gsutil ls gs://{bucket_name}", check=False)

    if success:
        print(f"  ✓ Bucket already exists: gs://{bucket_name}")
        return True

    # Create bucket
    print(f"  Creating bucket: gs://{bucket_name}")
    success, _, error = run_command(
        f"gsutil mb -p {get_current_project()} -l {region} gs://{bucket_name}",
        check=False
    )

    if success:
        print(f"    ✓ Created: gs://{bucket_name}")
        return True
    else:
        print(f"    ✗ Failed to create bucket: {error}")
        return False


def check_gpu_quota(project_id, region, gpu_type="nvidia-tesla-t4"):
    """Check GPU quota in the region"""
    print(f"\nChecking GPU quota for {gpu_type} in {region}...")

    # Get quota info
    success, output, _ = run_command(
        f"gcloud compute regions describe {region} --project={project_id}",
        check=False
    )

    if success:
        print(f"  Region {region} is available")
        print(f"\n  To check GPU quotas, visit:")
        print(f"  https://console.cloud.google.com/iam-admin/quotas?project={project_id}")
        print(f"\n  Search for: '{gpu_type.upper()}' in region '{region}'")
    else:
        print(f"  ✗ Could not verify region")


def create_gcp_config_file(project_id, region):
    """Create or update gcp_config.yaml"""
    config_path = "gcp_config.yaml"

    if os.path.exists(config_path):
        print(f"\n{config_path} already exists")
        response = input("Overwrite with new config? [y/N]: ")
        if response.lower() not in ['y', 'yes']:
            print("Keeping existing config")
            return

    config_content = f"""# GCP Batch Training Configuration
# Auto-generated by setup_gcp.py

gcp:
  project_id: "{project_id}"
  region: "{region}"
  zone: "{region}-a"

compute:
  machine_type: "n1-standard-4"
  gpu_type: "nvidia-tesla-t4"
  gpu_count: 1
  disk_size_gb: 100
  image_family: "pytorch-latest-gpu"
  image_project: "deeplearning-platform-release"

storage:
  training_data_bucket: "{project_id}-training-data"
  output_bucket: "{project_id}-lora-outputs"
  output_prefix: "lora-training-runs"

training:
  max_runtime_seconds: 7200
  retry_count: 1
  ai_toolkit_repo: "https://github.com/ostris/ai-toolkit.git"
  ai_toolkit_branch: "main"
  env_vars:
    HF_HOME: "/tmp/huggingface"
    TORCH_HOME: "/tmp/torch"

monitoring:
  enable_cloud_logging: true
  log_level: "INFO"

cost_control:
  use_preemptible: false
  max_concurrent_jobs: 5

advanced:
  additional_pip_packages:
    - "lpips"
    - "image-gen-aux"
"""

    with open(config_path, 'w') as f:
        f.write(config_content)

    print(f"\n✓ Created {config_path}")
    print(f"\nIMPORTANT: Review and customize {config_path} for your needs:")
    print(f"  - Adjust machine_type and gpu_type based on your requirements")
    print(f"  - Update bucket names if needed")
    print(f"  - Modify training parameters")


def main():
    parser = argparse.ArgumentParser(
        description="Setup GCP environment for Batch training",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )

    parser.add_argument(
        "--project",
        type=str,
        help="GCP project ID (uses current project if not specified)"
    )

    parser.add_argument(
        "--region",
        type=str,
        default="us-central1",
        help="GCP region (default: us-central1)"
    )

    parser.add_argument(
        "--create-buckets",
        action="store_true",
        help="Create GCS buckets"
    )

    parser.add_argument(
        "--skip-api-enable",
        action="store_true",
        help="Skip enabling APIs"
    )

    args = parser.parse_args()

    print("="*60)
    print("GCP Batch Training Setup")
    print("="*60)

    # Check gcloud installation
    print("\n1. Checking gcloud CLI...")
    if not check_gcloud_installed():
        print("  ✗ gcloud CLI not found")
        print("\n  Install from: https://cloud.google.com/sdk/docs/install")
        sys.exit(1)
    print("  ✓ gcloud CLI installed")

    # Check authentication
    print("\n2. Checking authentication...")
    if not check_authenticated():
        print("  ✗ Not authenticated with GCP")
        print("\n  Run: gcloud auth application-default login")
        sys.exit(1)
    print("  ✓ Authenticated")

    # Get project ID
    print("\n3. Determining GCP project...")
    if args.project:
        project_id = args.project
    else:
        project_id = get_current_project()

    if not project_id:
        print("  ✗ Could not determine project ID")
        print("\n  Specify with: --project YOUR_PROJECT_ID")
        print("  Or set default: gcloud config set project YOUR_PROJECT_ID")
        sys.exit(1)

    print(f"  ✓ Using project: {project_id}")

    # Enable APIs
    if not args.skip_api_enable:
        enable_apis(project_id)

    # Create config file
    print("\n4. Creating configuration file...")
    create_gcp_config_file(project_id, args.region)

    # Create buckets
    if args.create_buckets:
        print("\n5. Creating GCS buckets...")
        training_bucket = f"{project_id}-training-data"
        output_bucket = f"{project_id}-lora-outputs"

        create_bucket(training_bucket, args.region)
        create_bucket(output_bucket, args.region)
    else:
        print("\n5. Skipping bucket creation")
        print("  To create buckets, run with --create-buckets")

    # Check GPU quota
    check_gpu_quota(project_id, args.region)

    # Final instructions
    print("\n" + "="*60)
    print("Setup Complete!")
    print("="*60)

    print("\nNext steps:")
    print("  1. Review and customize gcp_config.yaml")

    if not args.create_buckets:
        print("  2. Create GCS buckets:")
        print(f"     gsutil mb gs://{project_id}-training-data")
        print(f"     gsutil mb gs://{project_id}-lora-outputs")

    print("  3. Verify GPU quotas in your region")
    print("  4. Test the setup:")
    print("     python launch_batch_training.py --verify-only")
    print("  5. Launch training:")
    print("     python launch_batch_training.py --all")

    print("\nUseful links:")
    print(f"  GCP Console: https://console.cloud.google.com/batch?project={project_id}")
    print(f"  Quotas: https://console.cloud.google.com/iam-admin/quotas?project={project_id}")


if __name__ == '__main__':
    main()
